[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://omegle-clone-backend-production-8f06.up.railway.app"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
