[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://your-railway-app.up.railway.app"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(self), microphone=(self)"
